//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: demofile.proto
namespace DotaIt.ReplayParser.Protobuf
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CGameInfo")]
    public partial class CGameInfo : global::ProtoBuf.IExtensible
    {
        public CGameInfo() { }

        private CGameInfo.CDotaGameInfo _dota = null;
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"dota", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public CGameInfo.CDotaGameInfo dota
        {
            get { return _dota; }
            set { _dota = value; }
        }
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CDotaGameInfo")]
        public partial class CDotaGameInfo : global::ProtoBuf.IExtensible
        {
            public CDotaGameInfo() { }

            private uint _match_id = default(uint);
            [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"match_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(uint))]
            public uint match_id
            {
                get { return _match_id; }
                set { _match_id = value; }
            }
            private int _game_mode = default(int);
            [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"game_mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int game_mode
            {
                get { return _game_mode; }
                set { _game_mode = value; }
            }
            private int _game_winner = default(int);
            [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"game_winner", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int game_winner
            {
                get { return _game_winner; }
                set { _game_winner = value; }
            }
            private readonly global::System.Collections.Generic.List<CGameInfo.CDotaGameInfo.CPlayerInfo> _player_info = new global::System.Collections.Generic.List<CGameInfo.CDotaGameInfo.CPlayerInfo>();
            [global::ProtoBuf.ProtoMember(4, Name = @"player_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public global::System.Collections.Generic.List<CGameInfo.CDotaGameInfo.CPlayerInfo> player_info
            {
                get { return _player_info; }
            }

            private uint _leagueid = default(uint);
            [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"leagueid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(uint))]
            public uint leagueid
            {
                get { return _leagueid; }
                set { _leagueid = value; }
            }
            private readonly global::System.Collections.Generic.List<CGameInfo.CDotaGameInfo.CHeroSelectEvent> _picks_bans = new global::System.Collections.Generic.List<CGameInfo.CDotaGameInfo.CHeroSelectEvent>();
            [global::ProtoBuf.ProtoMember(6, Name = @"picks_bans", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public global::System.Collections.Generic.List<CGameInfo.CDotaGameInfo.CHeroSelectEvent> picks_bans
            {
                get { return _picks_bans; }
            }

            private uint _radiant_team_id = default(uint);
            [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name = @"radiant_team_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(uint))]
            public uint radiant_team_id
            {
                get { return _radiant_team_id; }
                set { _radiant_team_id = value; }
            }
            private uint _dire_team_id = default(uint);
            [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name = @"dire_team_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(uint))]
            public uint dire_team_id
            {
                get { return _dire_team_id; }
                set { _dire_team_id = value; }
            }
            private string _radiant_team_tag = "";
            [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name = @"radiant_team_tag", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string radiant_team_tag
            {
                get { return _radiant_team_tag; }
                set { _radiant_team_tag = value; }
            }
            private string _dire_team_tag = "";
            [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name = @"dire_team_tag", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string dire_team_tag
            {
                get { return _dire_team_tag; }
                set { _dire_team_tag = value; }
            }
            private uint _end_time = default(uint);
            [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name = @"end_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(uint))]
            public uint end_time
            {
                get { return _end_time; }
                set { _end_time = value; }
            }
            [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CPlayerInfo")]
            public partial class CPlayerInfo : global::ProtoBuf.IExtensible
            {
                public CPlayerInfo() { }

                private string _hero_name = "";
                [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"hero_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
                [global::System.ComponentModel.DefaultValue("")]
                public string hero_name
                {
                    get { return _hero_name; }
                    set { _hero_name = value; }
                }
                private string _player_name = "";
                [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"player_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
                [global::System.ComponentModel.DefaultValue("")]
                public string player_name
                {
                    get { return _player_name; }
                    set { _player_name = value; }
                }
                private bool _is_fake_client = default(bool);
                [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"is_fake_client", DataFormat = global::ProtoBuf.DataFormat.Default)]
                [global::System.ComponentModel.DefaultValue(default(bool))]
                public bool is_fake_client
                {
                    get { return _is_fake_client; }
                    set { _is_fake_client = value; }
                }
                private ulong _steamid = default(ulong);
                [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"steamid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
                [global::System.ComponentModel.DefaultValue(default(ulong))]
                public ulong steamid
                {
                    get { return _steamid; }
                    set { _steamid = value; }
                }
                private int _game_team = default(int);
                [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"game_team", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
                [global::System.ComponentModel.DefaultValue(default(int))]
                public int game_team
                {
                    get { return _game_team; }
                    set { _game_team = value; }
                }
                private global::ProtoBuf.IExtension extensionObject;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
            }

            [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CHeroSelectEvent")]
            public partial class CHeroSelectEvent : global::ProtoBuf.IExtensible
            {
                public CHeroSelectEvent() { }

                private bool _is_pick = default(bool);
                [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"is_pick", DataFormat = global::ProtoBuf.DataFormat.Default)]
                [global::System.ComponentModel.DefaultValue(default(bool))]
                public bool is_pick
                {
                    get { return _is_pick; }
                    set { _is_pick = value; }
                }
                private uint _team = default(uint);
                [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"team", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
                [global::System.ComponentModel.DefaultValue(default(uint))]
                public uint team
                {
                    get { return _team; }
                    set { _team = value; }
                }
                private uint _hero_id = default(uint);
                [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"hero_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
                [global::System.ComponentModel.DefaultValue(default(uint))]
                public uint hero_id
                {
                    get { return _hero_id; }
                    set { _hero_id = value; }
                }
                private global::ProtoBuf.IExtension extensionObject;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
            }

            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CDemoFileInfo")]
    public partial class CDemoFileInfo : global::ProtoBuf.IExtensible
    {
        public CDemoFileInfo() { }

        private float _playback_time = default(float);
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"playback_time", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        [global::System.ComponentModel.DefaultValue(default(float))]
        public float playback_time
        {
            get { return _playback_time; }
            set { _playback_time = value; }
        }
        private int _playback_ticks = default(int);
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"playback_ticks", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int playback_ticks
        {
            get { return _playback_ticks; }
            set { _playback_ticks = value; }
        }
        private int _playback_frames = default(int);
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"playback_frames", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int playback_frames
        {
            get { return _playback_frames; }
            set { _playback_frames = value; }
        }
        private CGameInfo _game_info = null;
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"game_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public CGameInfo game_info
        {
            get { return _game_info; }
            set { _game_info = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

}